### ISSUE TITLE
Answers to Leaflet questions!

### ISSUE THREAD

**Issue by lyzidiamond** [livienyin/lexvlex#4]
These are questions @livienyin had about #3.

[4:40 PM] livien: are "L._______" leaflet functions?

[4:44 PM] livien: what's the difference between including "var" and not including "var" in "Fix variable definition error in style function"?

[5:02 PM] livien: For "function onEachFeature(feature, layer) {
 layer.on('click', function(e) {
   map.fitBounds(e.target.getBounds());
 });
 layer.bindPopup(popup(feature));
};" --> Where does the "e" come from and what type of an object is it?
1. L.__________: I'm not sure how to define this well, but I'll give it a try. (@eeeschwartz should jump in and explain it better!) Leaflet.js is an API that has a bunch of classes in it. One class is a "map": [`L.map` makes a map object](http://leafletjs.com/reference.html#map-constructor). The map has a series of options (which you see in the `{ }` [here](https://github.com/livienyin/lexvlex/blob/master/js/parks_map.js#L17-L22)) and a series of methods you can run on it. `L.geoJson` and `L.tileLayer` are also Leaflet objects: you can read more about them in the API doc [here](http://leafletjs.com/reference.html).
2. This change has to do with variable scope. By [defining the `tractColor` in the `style` function with `var`](https://github.com/livienyin/lexvlex/blob/master/js/parks_map.js#L27), it means that `tractColor` only has meaning inside of that function. Anything inside of the function knows what it is, but `tractColor` has no meaning outside of that function. If we decided we needed to access that variable elsewhere in the code, we could leave off the var, making it a "global variable" that can be accessed anywhere.
3. [The `layer.on('click')` method](https://github.com/livienyin/lexvlex/blob/master/js/parks_map.js#L52-L54) is an _event handler_. It says, "When someone clicks on the map, do this function." The Leaflet map class can have [quite a few events](http://leafletjs.com/reference.html#map-events). The `e` here represents the event itself -- in this case, click. The callback function that takes `e` as a parameter is creating an event handler for the click -- it says when you click, fit the bounds of the map to whatever was clicked on. `e.target.getBounds()` says take the click, find out what was clicked on (the `target`), and get the bounds of that object. That bounding box is then passed as an argument to the `map.fitBounds()` method, and the map zooms to that bounding box.

**Comment by livienyin** [comment]
This is great, super clear explanations :+1:  Let's leave it up for awhile incase it's needed for future reference/reminders.

**Comment by lyzidiamond** [comment]
:star2: :+1:
